default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>
  host: <%= ENV.fetch("DB_HOST", "db") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "contact_list_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DB", "contact_list_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_PRODUCTION_DB", "contact_list_production") %>
  username: <%= ENV.fetch("POSTGRES_PRODUCTION_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PRODUCTION_PASSWORD", "") %>
